spring:
  application:
    name: zuul

server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

zuul:
  retryable: true #开启重试
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
    
#以下是默认参数，不配置也可
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream